# Generated by Django 6.0.5 on 2026-06-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_note_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="reminder_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
