# Generated by Django 6.0.5 on 2026-05-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="color",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("red", "Red"),
                    ("orange", "Orange"),
                    ("yellow", "Yellow"),
                    ("green", "Green"),
                    ("teal", "Teal"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                    ("brown", "Brown"),
                    ("gray", "Gray"),
                ],
                default="default",
                max_length=20,
            ),
        ),
    ]
