[build]
builder = "NIXPACKS"

[deploy]
releaseCommand = "python manage.py migrate --no-input && python manage.py collectstatic --no-input"
startCommand = "gunicorn fundoonotes.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
healthcheckPath = "/api/schema/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[deploy.envVars]]
name = "DJANGO_SETTINGS_MODULE"
value = "fundoonotes.settings"
